# Generated by Django 4.2.20 on 2025-03-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("link", models.URLField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("pub_date", models.DateTimeField()),
            ],
        ),
    ]
