# Generated by Django 4.2.20 on 2025-03-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="link",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
