# Generated by Django 4.2.20 on 2025-07-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_category_alter_article_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("Technology", "Technology"),
                    ("Science", "Science"),
                    ("Business", "Business"),
                    ("Health", "Health"),
                    ("Education", "Education"),
                ],
                default="Technology",
                max_length=100,
            ),
        ),
    ]
